### ISSUE TITLE
Suggestion: how about locale(s)?

### ISSUE THREAD

**Issue by AngeloGulina** [mozzillation/checolo.re#31]
First of all, the project is AMAZING 😍

I am curator of an Instagram project ([Atlas Sicilia](https://www.instagram.com/atlas.sicilia/)) that has a data-driven / storytelling approach to telling about Sicily. We recently worked on [some data regarding Sicilian language](https://www.instagram.com/p/CKJW6nXhwxH/) and found out to be a pretty interesting topic for the community.

So I was wondering, in the aim of adding a bit more of playfulness to the project, would you be willing to have a localised version of the region? This means, I'd be eager to work on it for Sicily of course 😄 

Let me know what you think and thanks in advance!

PS. Did I say the project is AMAZING? 😍

**Comment by edoguido** [comment]
Hi Angelo! Thank you very much for your appreciation :) it is always nice to receive enthusiastic and positive feedback.

The team discussed the opportunity to add local dialects for each region, and we all agreed that although it's a nice idea, it's preferable to make the project more international, e.g. by adding English for tourists or foreign people living in Italy, rather than making it even more local.

We really appreciate your feedback and are sure you understand our approach!

**Comment by AngeloGulina** [comment]
Thanks for the reply @edoguido 🙌

I would say the 2 things are not mutually exclusive. Also, I would add that anyone could actually create a copy of the project to have their own locale so the proposal was meant in the spirit of keeping this a unique source. In any case, I surely understand the reasoning and the decision.

The proposal of the localisation can be anyways turned into a general one.
Let me know if you need help on the localisation and / or if you change your mind later!

Best of luck 🍀
